definitions:
  api.Meta:
    properties:
      error:
        type: string
      msg:
        description: Status int64  `json:"status"`
        type: string
    type: object
  api.Response:
    properties:
      data: {}
      meta:
        $ref: '#/definitions/api.Meta'
    type: object
info:
  contact: {}
paths:
  /api/v1/general/exec-command:
    post:
      description: 获取结果
      parameters:
      - description: 格式为：运维给的签名
        in: header
        name: ClientAuthSign
        required: true
        type: string
      - in: formData
        name: string
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"data":{},"meta":{msg":"Success"}}'
          schema:
            $ref: '#/definitions/api.Response'
        "401":
          description: '{"data":{}, "meta":{"msg":"错误信息", "error":"错误格式输出(如存在)"}}'
          schema:
            $ref: '#/definitions/api.Response'
        "403":
          description: '{"data":{}, "meta":{"msg":"错误信息", "error":"错误格式输出(如存在)"}}'
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: '{"data":{}, "meta":{"msg":"错误信息", "error":"错误格式输出(如存在)"}}'
          schema:
            $ref: '#/definitions/api.Response'
      summary: 在本机执行命令
      tags:
      - 通用相关
  /api/v1/ping1:
    get:
      description: 返回"Hello world"
      parameters:
      - description: 格式为：运维给的签名
        in: header
        name: ClientAuthSign
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Hello world"}'
          schema:
            type: ""
      summary: 测试Gin能否正常访问
      tags:
      - 测试相关
swagger: "2.0"
