serverSide:
  ip: "192.168.111.111"
  allowCidr: "172.16.12.0/24"
  domain: "www.abc.com"
  isSSL: "true" # 是否启用SSL
  port: 8080

auth:
  key: "arhgfdbgfghfgdsfsfgfds"

customCmd:
#  获取本机IP的命令
  localIpCmd: "awk '{printf $1}' /data/common/server_ip"
#  访问后返回本机IP的网址(获取本机IP命令获取失败后执行)
  localIpApi: "https://api.ipify.org/?format=text"
#  查询单服数量的命令
  gameSumCmd: 'find /data -maxdepth 1 -mindepth 1 -type d -regex ".*?_.*?_[a-zA-Z][0-9]+[a-zA-Z]" | wc -l'